import { width } from '@utils/constants';
import { StyleSheet } from 'react-native';

export const fullScreenLoginInputStyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    backgroundColor: '#fff',
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BDBDBD',
  },
  positionFixedLabel: {
    position: 'absolute',
    fontSize: 14,
    top: -0.5,
    left: 8,
    backgroundColor: '#fff',
    lineHeight: 50,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 5,
    height: '100%',
    zIndex: 0,
  },
  footerTextContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingTop: 16,
    gap: 4
  }
});

export const standardLoginInputStyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    // marginTop: 22,
  },
  modalView: {
    backgroundColor: 'white',
    borderTopStartRadius: 6,
    borderTopEndRadius: 6,
    paddingVertical: 20,
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
  },
  positionFixedLabel: {
    position: 'absolute',
    top: 0,
    left: 20,
    backgroundColor: '#fff',
    lineHeight: 50,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 5,
    height: '100%',
    zIndex: 0,
  },
  footerTextContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width,
    marginHorizontal: 20,
    paddingHorizontal: 20,
    paddingTop: 16,
    flexDirection: 'row',
    gap: 4
  },
  captionText: {
    color: '#BDBDBD',
    fontFamily: 'Roboto',
    fontSize: 11,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 13,
    letterSpacing: 0.165,
  },
  consentText: {
    color: '#424242',
    fontFamily: 'Roboto',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0.012,
  },
});

export const otpInputstyles = StyleSheet.create({
  containerStyle: {
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 2,
    paddingVertical: 8,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: '15%',
  },
  textInputStyle: {
    padding: 0,
    color: '#000',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'Roboto-Medium',
  },
});

export const otpModalstyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    // marginTop: 22,
  },
  modalView: {
    width,
    backgroundColor: 'white',
    borderTopStartRadius: 6,
    borderTopEndRadius: 6,
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginHorizontal: 20,
  },
  inputWrap: {
    position: 'relative',
    borderWidth: 1,
    color: '#000',
    borderColor: '#B3B3B3',
    borderRadius: 6,
    fontSize: 17,
    lineHeight: 18,
    letterSpacing: 0.27,
    width: '100%',
    alignSelf: 'center',
    paddingVertical: 12,
    zIndex: 1,
    paddingLeft: 12,
  },
  positionFixedLabel: {
    position: 'absolute',
    top: 0,
    left: 20,
    backgroundColor: '#fff',
    lineHeight: 50,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 5,
    height: '100%',
    zIndex: 0,
  },
});

export const resendOTPModalstyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    // marginTop: 22,
  },
  modalView: {
    width,
    backgroundColor: 'white',
    borderTopStartRadius: 6,
    borderTopEndRadius: 6,
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  inputWrap: {
    position: 'relative',
    borderWidth: 1,
    color: '#000',
    borderColor: '#B3B3B3',
    borderRadius: 6,
    fontSize: 17,
    lineHeight: 18,
    letterSpacing: 0.27,
    width: '100%',
    alignSelf: 'center',
    paddingVertical: 12,
    zIndex: 1,
    paddingLeft: 42,
  },
  positionFixedLabel: {
    position: 'absolute',
    top: 0,
    left: 20,
    backgroundColor: '#fff',
    lineHeight: 50,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 5,
    height: '100%',
    zIndex: 0,
  },
  radioContainerStyle: {
    width,
    marginBottom: 15,
  },
});

export const fullscreenOtpInputstyles = StyleSheet.create({
  enteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    backgroundColor: '#fff',
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BDBDBD',
  },
  positionFixedLabel: {
    position: 'absolute',
    fontSize: 14,
    top: 0,
    left: 8,
    backgroundColor: '#fff',
    lineHeight: 50,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 5,
    height: '100%',
    zIndex: 0,
  },
});

export const fullScreenResendOtpStyles = StyleSheet.create({
  enteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    backgroundColor: '#fff',
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BDBDBD',
  },
  inputWrap: {
    position: 'relative',
    borderWidth: 1,
    color: '#000',
    borderColor: '#B3B3B3',
    borderRadius: 6,
    fontSize: 17,
    lineHeight: 18,
    letterSpacing: 0.27,
    width: '100%',
    alignSelf: 'center',
    paddingVertical: 12,
    zIndex: 1,
    paddingLeft: 42,
  },
  positionFixedLabel: {
    position: 'absolute',
    fontSize: 14,
    top: -0.8,
    left: 8,
    backgroundColor: '#fff',
    lineHeight: 50,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 5,
    height: '100%',
    zIndex: 0,
  },
  radioContainerStyle: {
    width,
    marginBottom: 15,
  },
});
