import { StyleSheet } from 'react-native';

export const offersStyles = StyleSheet.create({
  offerGridList: {
    flexDirection: 'row',
  },
  offerGridListItem: {
    position: 'relative',
    backgroundColor: '#F1FFEE',
    borderColor: '#6BBD58',
    borderStyle: 'dashed',
    borderWidth: 1,
    width: 264,
    padding: 16,
    marginEnd: 4,
    borderRadius: 2,
  },
  offerListTitle: {
    paddingBottom: 8,
    minHeight: 35,
    overflow: 'hidden',
  },
  offerListDtl: {
    color: '#7E7E7E',
  },
  offerListCode: {
    fontSize: 14,
    fontFamily: 'Roboto-Medium',
    color: '#6BBD58',
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  UpTriangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'dashed',
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 5,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#6bbd58',
    position: 'absolute',
    bottom: -1,
    left: 50,
  },
  UpTriangleInner: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'dashed',
    borderLeftWidth: 4,
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FFFFFF',
    position: 'absolute',
    top: 1,
    right: -4,
    zIndex: 2,
  },
  DownTriangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'dashed',
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderTopWidth: 5,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#6bbd58',
    position: 'absolute',
    top: -1,
    left: 50,
  },
  DownTriangleInner: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'dashed',
    borderLeftWidth: 4,
    borderRightWidth: 4,
    borderTopWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#FFFFFF',
    position: 'absolute',
    bottom: 1,
    right: -4,
    zIndex: 2,
  },
  offerArrow: {
    position: 'absolute',
    right: 8,
    bottom: 10,
  },
  offerPopupHeader: {
    backgroundColor: '#fff',
    borderTopEndRadius: 8,
    borderTopStartRadius: 8,
    position: 'relative',
    top: -10,
    padding: 16,
    borderBottomColor: '#E0E0E0',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    marginBottom: 8,
    flexDirection: 'row',
  },
  offerPopupDtls: {
    padding: 16,
    paddingBottom: 0,
  },
  offerGridListPopup: {
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  offerCopyCode: {
    minHeight: 10,
    padding: 8,
    minWidth: 127,
  },
  copyText: {
    color: '#FF6F00',
    textTransform: 'uppercase',
    marginEnd: 0,
  },
  offerPopFooter: {
    borderTopColor: '#E0E0E0',
    borderTopWidth: 1,
    borderStyle: 'solid',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  closePpup: {
    position: 'absolute',
    right: 16,
    top: 16,
  },
});
